version: 2.1

executors:
  php82:
    docker:
      - image: cimg/php:8.2
    resource_class: small
  php83:
    docker:
      - image: cimg/php:8.3
    resource_class: small
  php84:
    docker:
      - image: cimg/php:8.4
    resource_class: small

jobs:
  analyse:
    executor: << parameters.php_executor >>
    parameters:
      php_executor:
        type: string
    steps:
      - checkout
      - run: composer update
      - run: composer analyse
  coverage:
    executor: php84
    steps:
      - run: sudo -E pecl install pcov && sudo -E docker-php-ext-enable pcov
      - checkout
      - run: composer update
      - run: composer coverage
  lint:
    executor: php84
    steps:
      - checkout
      - run: composer update
      - run: composer lint
  test:
    parameters:
      php_executor:
        type: string
    executor: << parameters.php_executor >>
    steps:
      - checkout
      - run: composer update --prefer-lowest
      - run: composer test
      - run: composer update
      - run: composer test

workflows:
  analyse_lint_test_coverage:
    jobs:
      - analyse:
          matrix:
            parameters:
              php_executor: [php82, php83, php84]
      - coverage
      - lint
      - test:
          matrix:
            parameters:
              php_executor: [php82, php83, php84]
